# Nome do Workflow
name: Generate Snake Animation

# Adicione esta seção de permissões aqui!
permissions: 
  contents: write

# Define quando a Action deve rodar
on:
  # Roda automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você rode essa Action manualmente pela aba "Actions"
  workflow_dispatch:

# Define as tarefas que serão executadas
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do seu repositório para que a Action possa acessar seus dados de contribuição
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de arquivos que serão gerados
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # Publica os arquivos gerados no seu repositório
      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
